baseURL = 'https://luoyunlingyu-mcbbs.github.io/mcbbs-hugo/'
languageCode = 'en'
title = '拯救MCBBS：论坛页面归档列表'
theme = 'etch-mc'

[params]
  description = "MC的精神，我们的世界!"
  copyright = "声明：所有网页均来自mcbbs论坛页面，其中内容与本站无关!"
  mainTitle = "MCBBS论坛页面归档列表"
  subTitle = "拯救MCBBS"
  Title = "拯救MCBBS：论坛页面归档列表"

[menu]
  [[menu.main]]
    identifier = "github"
    name = "Github仓库"
    title = "Github仓库"
    url = "https://github.com/luoyunlingyu-mcbbs/mcbbs-hugo"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "关于"
    title = "关于"
    url = "/about/"
    weight = 20
