baseURL = 'https://luoyunlingyu-mcbbs.github.io/mcbbs-hugo/'
languageCode = 'zh-CN'
title = '拯救MCBBS：论坛页面归档列表'
theme = 'etch'

[params]
  description = "MC的精神，我们的世界!"
  copyright = "声明：所有网页均来自mcbbs论坛页面，其中内容与本站无关!"
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "页面列表"
    title = "页面列表"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "关于"
    title = "关于"
    url = "/about/"
    weight = 20
